In [7]:
import open3d as o3d
import numpy as np
import os

In [14]:
# mesh_file_path = r'/home/yiting/Documents/Data/Shapes/stl_no_base/sheet/sheet_009.stl'
# mesh_file_path = r'/home/yiting/Documents/Data/Shapes/stl_no_base/axial_component/axial_component_025.stl'
mesh_file_path = r'/home/yiting/Documents/Data/Shapes/stl_no_base/torso/torso_068.stl'

mesh = o3d.io.read_triangle_mesh(mesh_file_path )

In [15]:
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

TriangleMesh with 54525 points and 25196 triangles.
Vertices:
[[ -0.54969895   8.73721504  -1.51783133]
 [ -1.21497321   9.61750317   0.20346878]
 [ -0.60868651   9.67479515   0.20346878]
 ...
 [-13.8021822    1.92012846  29.73663902]
 [-13.8065424    1.91996598  29.7203064 ]
 [-13.80891895   1.91653264  29.72475624]]
Triangles:
[[    0     1     2]
 [    0     3     1]
 [    4     5     6]
 ...
 [54516 54517 54518]
 [54519 54520 54521]
 [54522 54523 54524]]


In [16]:
# Visualize a 3D mesh
print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Try to render a mesh with normals (exist: True) and colors (exist: False)
A mesh with no normals and no colors does not look good.


In [17]:
# Surface normal estimation
print("Computing normal and rendering it.")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
o3d.visualization.draw_geometries([mesh])

Computing normal and rendering it.
[[-0.08258853  0.87398487 -0.47888368]
 [-0.08258978  0.87398457 -0.47888401]
 [-0.13735744  0.86706577 -0.47888399]
 ...
 [-0.64762378 -0.74540802  0.15795674]
 [-0.5984358   0.78938567  0.13691183]
 [-0.68736727  0.70454007  0.1764923 ]]


In [18]:
# Function to uniformly sample points from the mesh.
pcd = mesh.sample_points_uniformly(number_of_points=1024)
o3d.visualization.draw_geometries([pcd])



In [ ]:
save_dir = r'/home/yiting/Documents/Data/Shapes/ply_1024_jpg'

In [ ]:

# Sample points from the mesh
pcd = mesh.sample_points_uniformly(number_of_points=1024)

# Create a visualizer object
vis = o3d.visualization.Visualizer()
vis.create_window()

# Add the point cloud to the visualizer
vis.add_geometry(pcd)

# Poll events and update the renderer to make the geometry visible
vis.poll_events()
vis.update_renderer()

# Get the view control object to manipulate the view
view_control = vis.get_view_control()

# Rotate the view
view_control.rotate(0.0, 90.0)  # Rotate by (x-axis, y-axis) angle in degrees
# view_control.translate(0.0, 10.0)  # Optional: Translate the view if necessary



In [ ]:

# vis.capture_screen_image(os.path.join(save_dir,"point_cloud_visualization.png"))  # Save as PNG image

# Close the visualizer window
# vis.destroy_window()
