In [2]:
import open3d as o3d
import numpy as np
import os

In [3]:
mesh_file_path = r'/home/yiting/Documents/Data/Shapes/stl/sheet/sheet_009.stl'
mesh = o3d.io.read_triangle_mesh(mesh_file_path )

In [ ]:
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

In [6]:
# Visualize a 3D mesh
print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Try to render a mesh with normals (exist: True) and colors (exist: False)
A mesh with no normals and no colors does not look good.


In [7]:
# Surface normal estimation
print("Computing normal and rendering it.")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
o3d.visualization.draw_geometries([mesh])

Computing normal and rendering it.
[[-0.99445545 -0.01619832  0.10390369]
 [-0.99442694 -0.01962747  0.10358485]
 [-0.99470476  0.00551907  0.10262548]
 ...
 [ 0.00904326 -0.01760733  0.99980408]
 [ 0.02073408 -0.03588925  0.99914066]
 [ 0.04020491 -0.07149302  0.99663048]]


In [5]:
# Function to uniformly sample points from the mesh.
pcd = mesh.sample_points_uniformly(number_of_points=1024)
o3d.visualization.draw_geometries([pcd])



In [ ]:
save_dir = r'/home/yiting/Documents/Data/Shapes/ply_1024_jpg'

In [ ]:

# Sample points from the mesh
pcd = mesh.sample_points_uniformly(number_of_points=1024)

# Create a visualizer object
vis = o3d.visualization.Visualizer()
vis.create_window()

# Add the point cloud to the visualizer
vis.add_geometry(pcd)

# Poll events and update the renderer to make the geometry visible
vis.poll_events()
vis.update_renderer()

# Get the view control object to manipulate the view
view_control = vis.get_view_control()

# Rotate the view
view_control.rotate(0.0, 90.0)  # Rotate by (x-axis, y-axis) angle in degrees
# view_control.translate(0.0, 10.0)  # Optional: Translate the view if necessary



In [ ]:

# vis.capture_screen_image(os.path.join(save_dir,"point_cloud_visualization.png"))  # Save as PNG image

# Close the visualizer window
# vis.destroy_window()
