In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
mesh_file_path = r'/home/yiting/Documents/Data/Shapes/stl/sheet/sheet_009.stl'
mesh = o3d.io.read_triangle_mesh(mesh_file_path )

In [3]:
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

TriangleMesh with 32570 points and 13830 triangles.
Vertices:
[[ -7.27447033  -0.19147591  27.60905266]
 [ -7.39943361  -0.08288647  26.42996597]
 [ -7.38460541  -0.41500598  26.52010918]
 ...
 [-14.85800743 -14.85800838  -3.        ]
 [  2.5598886   -6.8793726   -3.1303072 ]
 [  2.50820994  -6.83196163  -3.12482142]]
Triangles:
[[    0     1     2]
 [    3     4     5]
 [    6     7     8]
 ...
 [32561 32562 32563]
 [32564 32565 32566]
 [32567 32568 32569]]


In [4]:
# Visualize a 3D mesh
print("Try to render a mesh with normals (exist: " +
      str(mesh.has_vertex_normals()) + ") and colors (exist: " +
      str(mesh.has_vertex_colors()) + ")")
o3d.visualization.draw_geometries([mesh])
print("A mesh with no normals and no colors does not look good.")

Try to render a mesh with normals (exist: True) and colors (exist: False)
A mesh with no normals and no colors does not look good.


In [5]:
# Surface normal estimation
print("Computing normal and rendering it.")
mesh.compute_vertex_normals()
print(np.asarray(mesh.triangle_normals))
o3d.visualization.draw_geometries([mesh])

Computing normal and rendering it.
[[-0.99445545 -0.01619832  0.10390369]
 [-0.99442694 -0.01962747  0.10358485]
 [-0.99470476  0.00551907  0.10262548]
 ...
 [ 0.00904326 -0.01760733  0.99980408]
 [ 0.02073408 -0.03588925  0.99914066]
 [ 0.04020491 -0.07149302  0.99663048]]


In [6]:
# Function to uniformly sample points from the mesh.
pcd = mesh.sample_points_uniformly(number_of_points=1024)
o3d.visualization.draw_geometries([pcd])



In [ ]:
# Save the point cloud in PLY format
o3d.io.write_point_cloud("output_point_cloud.ply", pcd)
